### ISSUE TITLE
CI file for Python monorepo

### ISSUE THREAD

**Issue by agamemnonc** [matakanobu/python-monorepo#2]
Excellent guide, thank you! 

Just a suggestion -- it would be incredibly useful to add a sample CI / GitHub Actions config file to demonstrate how CI would work with this approach.

**Comment by matakanobu** [comment]
@agamemnonc 
Thank you for your suggestion!

I completely agree that including a sample CI/GitHub Actions configuration file could significantly enhance the guide by providing a practical example of how CI could be integrated with this approach. 
OK, I will add a sample GitHub Actions configuration file to the repository, showcasing a basic CI workflow.

**Comment by matakanobu** [comment]
@agamemnonc 

I have implemented CI with GitHub Actions. As noted in the README, it detects changes on a per-project basis and performs build/test only for the projects that have changed.

The following are two examples of PRs. The first one is undergoing build/test, but the second one is not.

https://github.com/matakanobu/python-monorepo/pull/4
https://github.com/matakanobu/python-monorepo/pull/5

Lastly, thank you for the great suggestion.

**Comment by agamemnonc** [comment]
Awesome, thank you! :)
